# Change these first
owner: bomberosalas # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Personal
    url: https://www.csalas.cl
  - name: Mapas
    url: https://maps.csalas.cl
  - name: Segunda Cia Bomberos
    url: https://2da.cl
  - name: Bomberos Coyhaique
    url: https://bomberoscoyhaique.cl
  - name: Grifos
    url: https://grifos.cl

assignees: # Users to assign downtime issues (optional)
  - bomberosalas

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status Webs
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: sistema básico de monitoreo de de webs
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
